[package]
name = "fake_rules_rust_wasm_bindgen_lib"
version = "0.0.1"

[lib]
path = "fake_rules_rust_wasm_bindgen_lib.rs"

[dependencies]
wasm-bindgen = "0.2.68"

[raze]
genmode = "Remote"
workspace_path = "//wasm_bindgen/raze"
gen_workspace_prefix = "rules_rust_wasm_bindgen"
output_buildfile_suffix = "BUILD"

[raze.binary_deps]
wasm-bindgen-cli = "0.2.68"

[raze.crates.log.'0.3.9']
additional_flags = [
    "--cfg=atomic_cas",
    "--cfg=use_std",
]

[raze.crates.log.'0.4.11']
additional_flags = [
    "--cfg=atomic_cas",
    "--cfg=use_std",
]

[raze.crates.mime_guess.'1.8.8']
gen_buildrs = true

[raze.crates.openssl-sys.'0.9.58']
additional_flags = [
  # Vendored openssl is 1.0.2m
  "--cfg=ossl101",
  "--cfg=ossl102",
  "--cfg=ossl102f",
  "--cfg=ossl102h",
  "--cfg=ossl110",
  "--cfg=ossl110f",
  "--cfg=ossl110g",
  "--cfg=ossl111",
  "--cfg=ossl111b",
  "-l",
  "dylib=ssl",
  "-l",
  "dylib=crypto",
]

[raze.crates.proc-macro2.'1.0.23']
gen_buildrs = true
additional_flags = [
    "--cfg=use_proc_macro",
]

[raze.crates.proc-macro2.'1.0.24']
gen_buildrs = true
additional_flags = [
    "--cfg=use_proc_macro",
]

[raze.crates.syn.'1.0.40']
gen_buildrs = true

[raze.crates.syn.'1.0.45']
gen_buildrs = true

[raze.crates.serde_json.'1.0.57']
gen_buildrs = true

[raze.crates.unicase.'1.4.2']
additional_flags = [
  "--cfg=__unicase__iter_cmp",
  "--cfg=__unicase__defauler_hasher",
]

[raze.crates.wasm-bindgen.'0.2.68']
gen_buildrs = true

[raze.crates.wasm-bindgen-cli.'0.2.68']
gen_buildrs = true
extra_aliased_targets = ["cargo_bin_wasm_bindgen"]
