[package]
name = "rules_rust_examples_hello_sys"
version = "0.0.1"

[[bin]]
name = "rules_rust_examples_hello_sys"
path = "src/main.rs"

[dependencies]
bzip2 = "=0.3.3"

[raze]
workspace_path = "//hello_sys/raze"
genmode = "Remote"
incompatible_relative_workspace_path = true
gen_workspace_prefix = "rules_rust_examples_hello_sys"

[raze.crates.bzip2-sys.'0.1.9+1.0.8']
gen_buildrs = true
